export type DroneType =
  | 'FPV'
  | 'військовий'
  | 'професійний'
  | 'любительський'
  | 'сільськогосподарський'
  | 'кінематографічна'
  | 'системна'

export type ThreatLevel = 'низька' | 'середня' | 'висока' | 'критична'
export type Origin = 'Україна' | 'РФ' | 'Іран' | 'США' | 'Туреччина' | 'Китай' | 'Ізраїль' | 'Польща' | 'Міжнародний'

export type Drone = {
  id: number
  name: string
  type: DroneType
  origin: Origin
  range_km: number
  endurance_min: number
  payload_g: number
  weight_g: number
  speed_kmh: number
  battery_mah: number | null
  rotors?: number
  specs: string
  threat: ThreatLevel
}

export const droneDb: Drone[] = [
  // ── FPV ──────────────────────────────────────────────────────────────
  {
    id: 1,
    name: 'FPV 5" стандартний',
    type: 'FPV', origin: 'Україна',
    range_km: 5, endurance_min: 8, payload_g: 500, weight_g: 900, speed_kmh: 120,
    battery_mah: 1500, rotors: 4,
    specs: 'Стандартний 5" квадрокоптер. Заряд РПГ-7 або граната Ф-1/ВОГ-25. Час польоту 5–10 хв.',
    threat: 'висока',
  },
  {
    id: 2,
    name: 'FPV 7" камікадзе',
    type: 'FPV', origin: 'Україна',
    range_km: 8, endurance_min: 12, payload_g: 800, weight_g: 1500, speed_kmh: 120,
    battery_mah: 1300, rotors: 4,
    specs: '7" рама, ELRS/TBS, RTH, навантаження РПГ або кумулятивний заряд.',
    threat: 'критична',
  },
  {
    id: 3,
    name: 'FPV 10" (Shpak)',
    type: 'FPV', origin: 'Україна',
    range_km: 10, endurance_min: 15, payload_g: 5000, weight_g: 2000, speed_kmh: 150,
    battery_mah: 6000, rotors: 4,
    specs: '10" платформа. Несе до 5 кг (рекомендовано 2 кг). З ретранслятором — до 20 км.',
    threat: 'критична',
  },
  {
    id: 4,
    name: 'FPV 13" важкий бомбер',
    type: 'FPV', origin: 'Україна',
    range_km: 12, endurance_min: 20, payload_g: 4500, weight_g: 5000, speed_kmh: 80,
    battery_mah: 8000, rotors: 4,
    specs: 'Модифікований FPV з посиленою рамою. Несе РПГ-7 або 3+ кг вибухівки.',
    threat: 'критична',
  },
  {
    id: 5,
    name: 'VYRIY MAX 15',
    type: 'FPV', origin: 'Україна',
    range_km: 30, endurance_min: 20, payload_g: 8000, weight_g: 8000, speed_kmh: 100,
    battery_mah: 16000, rotors: 4,
    specs: '15" FPV платформа. Payload до 8 кг. За сприятливих умов — до 50 км з ретранслятором.',
    threat: 'критична',
  },
  {
    id: 6,
    name: 'Hornet Queen (Wild Hornets)',
    type: 'FPV', origin: 'Україна',
    range_km: 17, endurance_min: 25, payload_g: 9500, weight_g: 18000, speed_kmh: 60,
    battery_mah: null, rotors: 4,
    specs: '15" рама. ЗЛІТНА маса 18 кг, payload до 9.5 кг. Дві 6s4p батареї. 65% компонентів — українські.',
    threat: 'критична',
  },
  {
    id: 7,
    name: 'FPV 18" волоконно-оптичний',
    type: 'FPV', origin: 'Україна',
    range_km: 50, endurance_min: 25, payload_g: 6000, weight_g: 5000, speed_kmh: 120,
    battery_mah: 20000, rotors: 4,
    specs: 'Next-gen FPV з волоконно-оптичним управлінням. Повна стійкість до РЕБ. Дальність 50+ км.',
    threat: 'критична',
  },
  {
    id: 8,
    name: 'Caddx Vista FPV',
    type: 'FPV', origin: 'Китай',
    range_km: 3, endurance_min: 15, payload_g: 500, weight_g: 1200, speed_kmh: 180,
    battery_mah: 1500, rotors: 4,
    specs: 'HD FPV камера Vista. Використовується як база для ударних FPV.',
    threat: 'висока',
  },
  {
    id: 9,
    name: 'FPV «Баба Яга» (важкий аграрний)',
    type: 'FPV', origin: 'Україна',
    range_km: 10, endurance_min: 35, payload_g: 10000, weight_g: 15000, speed_kmh: 50,
    battery_mah: 22000, rotors: 6,
    specs: 'Модифікований сільськогосподарський дрон (DJI Agras тощо). Несе 10+ кг. Нічні атаки.',
    threat: 'критична',
  },

  // ── ВІЙСЬКОВІ ────────────────────────────────────────────────────────
  {
    id: 10,
    name: 'Vampire (SkyFall)',
    type: 'військовий', origin: 'Україна',
    range_km: 22, endurance_min: 37, payload_g: 15000, weight_g: 20000, speed_kmh: 80,
    battery_mah: 22000, rotors: 6,
    specs: 'Гексакоптер. З вантажем: 23 хв / 40 км/год. Без: 37 хв / 80 км/год. Тепловізор. #1 бомбер 2025 р.',
    threat: 'критична',
  },
  {
    id: 11,
    name: 'A1-SM Furia (Athlon Avia)',
    type: 'військовий', origin: 'Україна',
    range_km: 50, endurance_min: 240, payload_g: 1000, weight_g: 6500, speed_kmh: 150,
    battery_mah: 42000,
    specs: 'Складний корпус, запуск з пікапу. Батарея 2×42000 mAh. Камікадзе/розвідка.',
    threat: 'висока',
  },
  {
    id: 12,
    name: 'Leleka-100 (DeViRo)',
    type: 'військовий', origin: 'Україна',
    range_km: 80, endurance_min: 300, payload_g: 2000, weight_g: 5500, speed_kmh: 120,
    battery_mah: 14000,
    specs: 'Оновлена версія: радіус 80 км, маршрут до 340 км, 5 год. Стійкість до РЕБ. Катапульта/парашут.',
    threat: 'висока',
  },
  {
    id: 13,
    name: 'RAM II UAV (DeViRo)',
    type: 'військовий', origin: 'Україна',
    range_km: 30, endurance_min: 60, payload_g: 5000, weight_g: 3500, speed_kmh: 130,
    battery_mah: 14000,
    specs: 'Камікадзе на базі Лелека-100. Запуск з мобільної катапульти. Дальність до 30 км.',
    threat: 'висока',
  },
  {
    id: 14,
    name: 'PD-2 (UkrSpecSystems)',
    type: 'військовий', origin: 'Україна',
    range_km: 200, endurance_min: 600, payload_g: 8000, weight_g: 25000, speed_kmh: 100,
    battery_mah: null,
    specs: 'VTOL, 10 год польоту. AES 256 шифрування, стійкість до РЕБ. Дальність до 1300 км.',
    threat: 'висока',
  },
  {
    id: 15,
    name: 'Bayraktar TB2',
    type: 'військовий', origin: 'Туреччина',
    range_km: 150, endurance_min: 1620, payload_g: 55000, weight_g: 650000, speed_kmh: 220,
    battery_mah: null,
    specs: 'Двигун Rotax 912. 4 боєприпаси MAM-L/MAM-C. 27 год польоту. Оптика Aselsan.',
    threat: 'висока',
  },
  {
    id: 16,
    name: 'Switchblade 300 (AeroVironment)',
    type: 'військовий', origin: 'США',
    range_km: 10, endurance_min: 15, payload_g: 2000, weight_g: 2500, speed_kmh: 157,
    battery_mah: 3000,
    specs: 'Барражуючий боєприпас. Запуск з тубуса. Оператор може скасувати удар. Тандемна БЧ.',
    threat: 'висока',
  },
  {
    id: 17,
    name: 'Switchblade 600 (AeroVironment)',
    type: 'військовий', origin: 'США',
    range_km: 40, endurance_min: 40, payload_g: 5000, weight_g: 22700, speed_kmh: 185,
    battery_mah: 10000,
    specs: 'Більший варіант. Кумулятивна БЧ для ураження танків. Активна ГСН. Автопілот.',
    threat: 'висока',
  },
  {
    id: 18,
    name: 'Phoenix Ghost (AEVEX)',
    type: 'військовий', origin: 'США',
    range_km: 400, endurance_min: 360, payload_g: 8000, weight_g: 5900, speed_kmh: 200,
    battery_mah: 8000,
    specs: 'Барражуючий боєприпас. 6+ год польоту. Нічне бачення. Атака зверху (даху).',
    threat: 'висока',
  },
  {
    id: 19,
    name: 'Shahed-136 / «Герань-2»',
    type: 'військовий', origin: 'Іран',
    range_km: 1800, endurance_min: 584, payload_g: 40000, weight_g: 200000, speed_kmh: 185,
    battery_mah: null,
    specs: 'Поршневий двигун. Х-подібне крило. Летить зграями. Удари по інфраструктурі.',
    threat: 'критична',
  },
  {
    id: 20,
    name: 'Shahed-131 / «Герань-1»',
    type: 'військовий', origin: 'Іран',
    range_km: 900, endurance_min: 318, payload_g: 15000, weight_g: 36000, speed_kmh: 170,
    battery_mah: null,
    specs: 'Менший варіант Shahed-136. БЧ 15 кг. Менший радарний переріз.',
    threat: 'критична',
  },
  {
    id: 21,
    name: 'Lancet-3 / «Ланцет»',
    type: 'військовий', origin: 'РФ',
    range_km: 40, endurance_min: 40, payload_g: 3000, weight_g: 12000, speed_kmh: 300,
    battery_mah: 4400,
    specs: 'Барражуючий боєприпас РФ. Тандемна кумулятивна БЧ. Оператор керує до удару.',
    threat: 'критична',
  },
  {
    id: 22,
    name: 'Lancet-1',
    type: 'військовий', origin: 'РФ',
    range_km: 25, endurance_min: 30, payload_g: 1000, weight_g: 5000, speed_kmh: 110,
    battery_mah: 4000,
    specs: 'Менший варіант Lancet. Проти легкоброньованої техніки і піхоти.',
    threat: 'критична',
  },
  {
    id: 23,
    name: 'Orlan-10',
    type: 'військовий', origin: 'РФ',
    range_km: 120, endurance_min: 960, payload_g: 5000, weight_g: 14000, speed_kmh: 150,
    battery_mah: null,
    specs: 'Бензиновий двигун Saito. Коригує вогонь артилерії та РСЗВ. Підвищує точність у 10×.',
    threat: 'критична',
  },
  {
    id: 24,
    name: 'Orlan-30',
    type: 'військовий', origin: 'РФ',
    range_km: 150, endurance_min: 600, payload_g: 8000, weight_g: 25000, speed_kmh: 180,
    battery_mah: null,
    specs: 'Лазерний далекомір + ретранслятор. Наводить ПТРК. Цифровий канал.',
    threat: 'критична',
  },
  {
    id: 25,
    name: 'ZALA 421-16E5',
    type: 'військовий', origin: 'РФ',
    range_km: 15, endurance_min: 40, payload_g: 500, weight_g: 2500, speed_kmh: 130,
    battery_mah: 14000,
    specs: 'Малий розвідувальний. Складаний, запускається вручну. Тихий двигун.',
    threat: 'висока',
  },
  {
    id: 26,
    name: 'Granat-4',
    type: 'військовий', origin: 'РФ',
    range_km: 120, endurance_min: 240, payload_g: 3500, weight_g: 14000, speed_kmh: 130,
    battery_mah: 18000,
    specs: 'Розвідувальний БПЛА. ІЧ сенсори. Катапультний запуск. Тривала розвідка позицій.',
    threat: 'висока',
  },
  {
    id: 27,
    name: 'Supercam S350',
    type: 'військовий', origin: 'РФ',
    range_km: 100, endurance_min: 240, payload_g: 1000, weight_g: 3500, speed_kmh: 120,
    battery_mah: 16000,
    specs: 'Гібридний двигун. Поліпшені сенсори. Цифровий канал, стійкість до РЕБ.',
    threat: 'висока',
  },
  {
    id: 28,
    name: 'Mohajer-6 (Іран/РФ)',
    type: 'військовий', origin: 'Іран',
    range_km: 200, endurance_min: 720, payload_g: 100000, weight_g: 100000, speed_kmh: 200,
    battery_mah: null,
    specs: 'Ударний БПЛА з ракетами Qaem-5. Значно потужніший за FPV.',
    threat: 'критична',
  },

  // ── ПРОФЕСІЙНІ ──────────────────────────────────────────────────────
  {
    id: 29,
    name: 'DJI Mavic 3',
    type: 'професійний', origin: 'Китай',
    range_km: 25, endurance_min: 46, payload_g: 1170, weight_g: 915, speed_kmh: 75,
    battery_mah: 5000, rotors: 4,
    specs: '4/3" CMOS, 4K 120fps. OcuSync 3. Широко використовується обома сторонами.',
    threat: 'висока',
  },
  {
    id: 30,
    name: 'DJI Mavic 3T (тепловізійний)',
    type: 'професійний', origin: 'Китай',
    range_km: 15, endurance_min: 45, payload_g: 0, weight_g: 1050, speed_kmh: 68,
    battery_mah: 5000, rotors: 4,
    specs: 'DJI Mavic 3 Thermal. 48 Мп + тепловізор FLIR. Розвідка і пошук особового складу вночі.',
    threat: 'критична',
  },
  {
    id: 31,
    name: 'DJI M300 RTK',
    type: 'професійний', origin: 'Китай',
    range_km: 8, endurance_min: 55, payload_g: 2700, weight_g: 9000, speed_kmh: 77,
    battery_mah: 5935, rotors: 6,
    specs: 'Гаряча заміна батареї, IP45. Промислова платформа з підвісами.',
    threat: 'критична',
  },
  {
    id: 32,
    name: 'DJI M350 RTK',
    type: 'професійний', origin: 'Китай',
    range_km: 10, endurance_min: 60, payload_g: 4500, weight_g: 9000, speed_kmh: 77,
    battery_mah: 5880, rotors: 6,
    specs: 'ModuleQ система, RTK. Промислова платформа нового покоління.',
    threat: 'критична',
  },
  {
    id: 33,
    name: 'DJI Air 3S',
    type: 'професійний', origin: 'Китай',
    range_km: 25, endurance_min: 46, payload_g: 2000, weight_g: 729, speed_kmh: 75,
    battery_mah: 4241, rotors: 4,
    specs: 'Thermal + 4K. Компактна розвідувальна платформа.',
    threat: 'висока',
  },
  {
    id: 34,
    name: 'DJI Phantom 4 Pro',
    type: 'професійний', origin: 'Китай',
    range_km: 7, endurance_min: 30, payload_g: 1375, weight_g: 1280, speed_kmh: 72,
    battery_mah: 5870, rotors: 4,
    specs: '1" CMOS 4K. Все ще активно використовується для розвідки.',
    threat: 'середня',
  },

  // ── ЛЮБИТЕЛЬСЬКІ ────────────────────────────────────────────────────
  {
    id: 35,
    name: 'DJI Mini 3 Pro',
    type: 'любительський', origin: 'Китай',
    range_km: 20, endurance_min: 38, payload_g: 500, weight_g: 250, speed_kmh: 57,
    battery_mah: 2453, rotors: 4,
    specs: '1/1.3" CMOS, 4K. Широко доступний, використовується для розвідки.',
    threat: 'середня',
  },
  {
    id: 36,
    name: 'Parrot Anafi',
    type: 'любительський', origin: 'Міжнародний',
    range_km: 4, endurance_min: 25, payload_g: 320, weight_g: 320, speed_kmh: 55,
    battery_mah: 2700, rotors: 4,
    specs: 'Складний 4K. Легкий та компактний.',
    threat: 'середня',
  },

  // ── СІЛЬСЬКОГОСПОДАРСЬКІ ─────────────────────────────────────────────
  {
    id: 37,
    name: 'DJI Agras T30',
    type: 'сільськогосподарський', origin: 'Китай',
    range_km: 3, endurance_min: 22, payload_g: 30000, weight_g: 28000, speed_kmh: 50,
    battery_mah: 30000, rotors: 8,
    specs: '30 л бак, дельта крила. Адаптується для скидання боєприпасів.',
    threat: 'критична',
  },
  {
    id: 38,
    name: 'DJI Agras T20',
    type: 'сільськогосподарський', origin: 'Китай',
    range_km: 2, endurance_min: 20, payload_g: 20000, weight_g: 18000, speed_kmh: 45,
    battery_mah: 18000, rotors: 6,
    specs: '20 л бак, прямі крила. Використовується як «Баба Яга».',
    threat: 'критична',
  },

  // ── КІНЕМАТОГРАФІЧНІ ────────────────────────────────────────────────
  {
    id: 39,
    name: 'Freefly Cinestar 8',
    type: 'кінематографічна', origin: 'Міжнародний',
    range_km: 2, endurance_min: 15, payload_g: 10000, weight_g: 11000, speed_kmh: 40,
    battery_mah: 22000, rotors: 8,
    specs: 'Великий кіно-підйомник. Потенційно може використовуватися для скидів.',
    threat: 'критична',
  },

  // ── СИСТЕМНІ ────────────────────────────────────────────────────────
  {
    id: 40,
    name: 'Auterion Skynode',
    type: 'системна', origin: 'Міжнародний',
    range_km: 5, endurance_min: 30, payload_g: 2000, weight_g: 3500, speed_kmh: 65,
    battery_mah: 12000, rotors: 4,
    specs: 'Автономна системна платформа. Відкритий PX4 автопілот.',
    threat: 'висока',
  },

  // ── FPV (розширення) ──────────────────────────────────────────────
  {
    id: 41,
    name: 'FPV "Жало" 5"',
    type: 'FPV', origin: 'Україна',
    range_km: 4, endurance_min: 7, payload_g: 400, weight_g: 750, speed_kmh: 140,
    battery_mah: 1300, rotors: 4,
    specs: 'Мінімалістичний ударний 5" FPV. Legit F4/F7 FC, RunCam ELRS. Збірки від волонтерів.',
    threat: 'висока',
  },
  {
    id: 42,
    name: 'FPV "Бджола" 3.5" міні',
    type: 'FPV', origin: 'Україна',
    range_km: 2, endurance_min: 6, payload_g: 150, weight_g: 380, speed_kmh: 130,
    battery_mah: 650, rotors: 4,
    specs: 'Малий 3.5" ударний дрон для дій у приміщеннях та вузьких коридорах. Граната Ф-1.',
    threat: 'висока',
  },
  {
    id: 43,
    name: 'Gepard FPV 5"',
    type: 'FPV', origin: 'Україна',
    range_km: 6, endurance_min: 9, payload_g: 500, weight_g: 850, speed_kmh: 150,
    battery_mah: 1500, rotors: 4,
    specs: 'Серійний ударний FPV. ELRS 900 MHz. Використовує стандартні 5" запасні частини.',
    threat: 'висока',
  },
  {
    id: 44,
    name: 'FPV "Упирь" (РФ)',
    type: 'FPV', origin: 'РФ',
    range_km: 5, endurance_min: 8, payload_g: 500, weight_g: 900, speed_kmh: 120,
    battery_mah: 1500, rotors: 4,
    specs: 'Російський ударний FPV. Аналог українських. Масово виробляється.',
    threat: 'висока',
  },
  {
    id: 45,
    name: 'FPV "Зміє-Горинич" 7"',
    type: 'FPV', origin: 'РФ',
    range_km: 7, endurance_min: 12, payload_g: 700, weight_g: 1400, speed_kmh: 110,
    battery_mah: 2200, rotors: 4,
    specs: 'Посилений 7" FPV РФ. Кумулятивна БЧ або РПГ-7ВЛ. З ретранслятором до 15 км.',
    threat: 'критична',
  },
  {
    id: 46,
    name: 'DJI FPV Combo',
    type: 'FPV', origin: 'Китай',
    range_km: 10, endurance_min: 20, payload_g: 0, weight_g: 795, speed_kmh: 140,
    battery_mah: 2000, rotors: 4,
    specs: 'Комерційний гоночний FPV DJI. O3 відео 4K. Використовується як база для FPV камікадзе.',
    threat: 'середня',
  },

  // ── УКРАЇНСЬКІ ВІЙСЬКОВІ (розширення) ────────────────────────────
  {
    id: 47,
    name: 'UJ-22 Airborne (UkrJet)',
    type: 'військовий', origin: 'Україна',
    range_km: 800, endurance_min: 360, payload_g: 20000, weight_g: 60000, speed_kmh: 200,
    battery_mah: null,
    specs: 'Стратегічний ударний БПЛА. ДВЗ, взлітна маса 60 кг, дальність 800 км. Атаки вглиб РФ.',
    threat: 'критична',
  },
  {
    id: 48,
    name: 'R18 Octocopter (UA Dynamics)',
    type: 'військовий', origin: 'Україна',
    range_km: 10, endurance_min: 30, payload_g: 5000, weight_g: 10000, speed_kmh: 50,
    battery_mah: 22000, rotors: 8,
    specs: 'Важкий октокоптер. Несе 5 кг: РПГ або 4 × ВОГ-17. Тепловізор. ЗСУ #1 бомбер 2023.',
    threat: 'критична',
  },
  {
    id: 49,
    name: 'AQ-400 Scythe',
    type: 'військовий', origin: 'Україна',
    range_km: 750, endurance_min: 240, payload_g: 32000, weight_g: 55000, speed_kmh: 160,
    battery_mah: null,
    specs: 'Ударний БПЛА класу "довгі руки". Атаки нафтопереробних заводів РФ. ДВЗ.',
    threat: 'критична',
  },
  {
    id: 50,
    name: 'Punisher UAS (UA Dynamics)',
    type: 'військовий', origin: 'Україна',
    range_km: 100, endurance_min: 180, payload_g: 3000, weight_g: 6700, speed_kmh: 130,
    battery_mah: null,
    specs: 'Тактичний ударний безпілотник. Три бомби ТП-1 (1.5 кг кожна). Катапультний запуск.',
    threat: 'висока',
  },
  {
    id: 51,
    name: 'Spectator M-1',
    type: 'військовий', origin: 'Україна',
    range_km: 50, endurance_min: 120, payload_g: 1500, weight_g: 4500, speed_kmh: 120,
    battery_mah: null,
    specs: 'Розвідувальний БПЛА. ЕО/ІЧ підвіс. Катапультний запуск, парашутна посадка.',
    threat: 'висока',
  },
  {
    id: 52,
    name: 'Shark / "Акула" (Hero Systems)',
    type: 'військовий', origin: 'Україна',
    range_km: 75, endurance_min: 270, payload_g: 2000, weight_g: 5500, speed_kmh: 180,
    battery_mah: null,
    specs: 'Стратегічний розвідувальний БПЛА. Морські операції. 4.5 год польоту.',
    threat: 'висока',
  },
  {
    id: 53,
    name: '"Лютий" (UKRJET)',
    type: 'військовий', origin: 'Україна',
    range_km: 1000, endurance_min: 480, payload_g: 75000, weight_g: 150000, speed_kmh: 280,
    battery_mah: null,
    specs: 'Реактивний ударний БПЛА. Турбореактивний двигун. Атаки об\'єктів глибоко в РФ.',
    threat: 'критична',
  },
  {
    id: 54,
    name: 'Valkyria-1 (Ukrainian)',
    type: 'військовий', origin: 'Україна',
    range_km: 50, endurance_min: 40, payload_g: 3000, weight_g: 8000, speed_kmh: 120,
    battery_mah: null,
    specs: 'Важкий ударний БПЛА. Payload 3 кг. Катапульта/автономний зліт. Серійне виробництво.',
    threat: 'критична',
  },
  {
    id: 55,
    name: 'Bayraktar Akıncı',
    type: 'військовий', origin: 'Туреччина',
    range_km: 300, endurance_min: 1440, payload_g: 1350000, weight_g: 5500000, speed_kmh: 361,
    battery_mah: null,
    specs: '2 × турбогвинтові двигуни. 24 год польоту. Ракети Roketsan SOM. AESA радар.',
    threat: 'висока',
  },
  {
    id: 56,
    name: 'Bayraktar Mini UAV',
    type: 'військовий', origin: 'Туреччина',
    range_km: 5, endurance_min: 60, payload_g: 700, weight_g: 2100, speed_kmh: 72,
    battery_mah: 8000,
    specs: 'Тактичний розвідник. Електричний. Ручний запуск. EO/IR камера.',
    threat: 'середня',
  },

  // ── РОСІЙСЬКІ ВІЙСЬКОВІ (розширення) ─────────────────────────────
  {
    id: 57,
    name: 'Orion (Kronshtadt)',
    type: 'військовий', origin: 'РФ',
    range_km: 300, endurance_min: 1440, payload_g: 200000, weight_g: 1000000, speed_kmh: 200,
    battery_mah: null,
    specs: 'Важкий ударний БПЛА РФ. 24 год польоту. Ракети X-25. Аналог MQ-9.',
    threat: 'критична',
  },
  {
    id: 58,
    name: 'Forpost-RU',
    type: 'військовий', origin: 'РФ',
    range_km: 250, endurance_min: 1080, payload_g: 30000, weight_g: 375000, speed_kmh: 200,
    battery_mah: null,
    specs: 'Ліцензійна копія ізраїльського IAI Searcher II. Розвідка і коригування вогню.',
    threat: 'критична',
  },
  {
    id: 59,
    name: 'Eleron-3SV',
    type: 'військовий', origin: 'РФ',
    range_km: 25, endurance_min: 90, payload_g: 1000, weight_g: 2800, speed_kmh: 130,
    battery_mah: 14000,
    specs: 'Міні-БПЛА розвідки. Запуск вручну. Широко застосовується в ротних ланках РФ.',
    threat: 'висока',
  },
  {
    id: 60,
    name: 'Korsar',
    type: 'військовий', origin: 'РФ',
    range_km: 120, endurance_min: 480, payload_g: 6000, weight_g: 14500, speed_kmh: 150,
    battery_mah: null,
    specs: 'Тактичний розвідувальний БПЛА. Катапульта. ЕО/ТПВ підвіс. ТТН "РОЭЛЕКТРОНІКА".',
    threat: 'висока',
  },
  {
    id: 61,
    name: 'Kub-BLA (ZALA Aero)',
    type: 'військовий', origin: 'РФ',
    range_km: 40, endurance_min: 30, payload_g: 3000, weight_g: 40000, speed_kmh: 130,
    battery_mah: null,
    specs: 'Барражуючий боєприпас РФ. 3 кг БЧ. Авіаційний електромотор. Аналог Switchblade.',
    threat: 'критична',
  },
  {
    id: 62,
    name: 'ZALA 421-08M',
    type: 'військовий', origin: 'РФ',
    range_km: 15, endurance_min: 90, payload_g: 500, weight_g: 2700, speed_kmh: 130,
    battery_mah: 10000,
    specs: 'Електричний тактичний розвідник. Складне крило, ручний запуск. Підрозділи РФ.',
    threat: 'висока',
  },
  {
    id: 63,
    name: 'Shahed-238 (реактивний)',
    type: 'військовий', origin: 'Іран',
    range_km: 1500, endurance_min: 450, payload_g: 50000, weight_g: 250000, speed_kmh: 650,
    battery_mah: null,
    specs: 'Реактивна версія Shahed-136. Турбореактивний двигун. Ракетна БЧ. Складніше збити.',
    threat: 'критична',
  },
  {
    id: 64,
    name: 'Shahed-149 Gaza',
    type: 'військовий', origin: 'Іран',
    range_km: 2000, endurance_min: 1200, payload_g: 500000, weight_g: 3000000, speed_kmh: 250,
    battery_mah: null,
    specs: 'Іранський стратегічний БПЛА. Турбопропелер. Ракети Sadid-345. 20 год польоту.',
    threat: 'критична',
  },
  {
    id: 65,
    name: 'Qasef-2K',
    type: 'військовий', origin: 'Іран',
    range_km: 150, endurance_min: 60, payload_g: 30000, weight_g: 90000, speed_kmh: 180,
    battery_mah: null,
    specs: 'Барражуючий боєприпас Хуті/Ірану. Атаки Саудівської Аравії та ОАЕ. Копія CH-3.',
    threat: 'висока',
  },

  // ── США / НАТО ───────────────────────────────────────────────────
  {
    id: 66,
    name: 'MQ-9 Reaper (General Atomics)',
    type: 'військовий', origin: 'США',
    range_km: 1850, endurance_min: 1080, payload_g: 1700000, weight_g: 4763000, speed_kmh: 482,
    battery_mah: null,
    specs: 'Великий ударний БПЛА ВПС США. Hellfires + GBU-12. Турбопропелер 900 к.с.',
    threat: 'висока',
  },
  {
    id: 67,
    name: 'RQ-11B Raven (AeroVironment)',
    type: 'військовий', origin: 'США',
    range_km: 10, endurance_min: 60, payload_g: 200, weight_g: 1900, speed_kmh: 65,
    battery_mah: 5500,
    specs: 'Міні-БПЛА розвідки. Ручний запуск. EO/IR. Стандарт NATO. Батарея LiSO₂.',
    threat: 'низька',
  },
  {
    id: 68,
    name: 'RQ-20 Puma AE (AeroVironment)',
    type: 'військовий', origin: 'США',
    range_km: 15, endurance_min: 120, payload_g: 450, weight_g: 5900, speed_kmh: 83,
    battery_mah: 8000,
    specs: 'Малий розвідувальний БПЛА. Посадка на воду. EO/IR підвіс. ВМФ США та ЗСУ.',
    threat: 'низька',
  },
  {
    id: 69,
    name: 'RQ-7B Shadow 200',
    type: 'військовий', origin: 'США',
    range_km: 125, endurance_min: 480, payload_g: 27000, weight_g: 170000, speed_kmh: 204,
    battery_mah: null,
    specs: 'Тактичний БПЛА батальйонного рівня. Двигун Wankel AR801. EO/IR/лазер.',
    threat: 'середня',
  },
  {
    id: 70,
    name: 'Altius-600 (Area-I)',
    type: 'військовий', origin: 'США',
    range_km: 440, endurance_min: 270, payload_g: 12700, weight_g: 27200, speed_kmh: 278,
    battery_mah: null,
    specs: 'Тактичний ударний БПЛА. Запуск з тубуса. MADL зв\'язок. Для передових підрозділів.',
    threat: 'висока',
  },

  // ── ІЗРАЇЛЬ ───────────────────────────────────────────────────────
  {
    id: 71,
    name: 'IAI Harop',
    type: 'військовий', origin: 'Ізраїль',
    range_km: 1000, endurance_min: 360, payload_g: 23000, weight_g: 135000, speed_kmh: 417,
    battery_mah: null,
    specs: 'Барражуючий боєприпас. Пасивна ГСН (ЕМВ). 6 год барражування. Азербайджан, Індія.',
    threat: 'висока',
  },
  {
    id: 72,
    name: 'Elbit Hermes 450',
    type: 'військовий', origin: 'Ізраїль',
    range_km: 200, endurance_min: 1020, payload_g: 150000, weight_g: 550000, speed_kmh: 176,
    battery_mah: null,
    specs: 'Тактичний БПЛА. 17 год польоту. EO/IR/SAR. Ракети Spike ER. Бригадний рівень.',
    threat: 'висока',
  },
  {
    id: 73,
    name: 'IAI Bird-Eye 650D',
    type: 'військовий', origin: 'Ізраїль',
    range_km: 60, endurance_min: 240, payload_g: 2500, weight_g: 11000, speed_kmh: 140,
    battery_mah: null,
    specs: 'Компактний тактичний БПЛА. Електричний двигун. EO/IR. Батальйонний рівень.',
    threat: 'середня',
  },
  {
    id: 74,
    name: 'IAI Heron 1',
    type: 'військовий', origin: 'Ізраїль',
    range_km: 350, endurance_min: 2520, payload_g: 250000, weight_g: 1150000, speed_kmh: 207,
    battery_mah: null,
    specs: 'Середній стратегічний БПЛА. 42 год польоту. SAR/EO/SIGINT. NATO STANAG 4671.',
    threat: 'висока',
  },

  // ── ПОЛЬЩА ──────────────────────────────────────────────────────
  {
    id: 75,
    name: 'WB Group FlyEye',
    type: 'військовий', origin: 'Польща',
    range_km: 30, endurance_min: 180, payload_g: 1000, weight_g: 11000, speed_kmh: 140,
    battery_mah: null,
    specs: 'Польський тактичний БПЛА. Електричний. Ручний запуск. EO/IR. Поставлений Україні.',
    threat: 'середня',
  },

  // ── КИТАЙ (розширення) ───────────────────────────────────────────
  {
    id: 76,
    name: 'DJI Mavic 3 Enterprise',
    type: 'професійний', origin: 'Китай',
    range_km: 15, endurance_min: 45, payload_g: 0, weight_g: 915, speed_kmh: 75,
    battery_mah: 5000, rotors: 4,
    specs: 'Корпоративна версія Mavic 3. Кріплення аксесуарів, RTK. Гучномовець/прожектор.',
    threat: 'висока',
  },
  {
    id: 77,
    name: 'Autel EVO Max 4T',
    type: 'професійний', origin: 'Китай',
    range_km: 20, endurance_min: 42, payload_g: 0, weight_g: 1580, speed_kmh: 72,
    battery_mah: 7100, rotors: 4,
    specs: '50 Мп + тепловізор FLIR 640px + LiDAR. Аналог Mavic 3T. Широко використовується.',
    threat: 'висока',
  },
  {
    id: 78,
    name: 'DJI Agras T50',
    type: 'сільськогосподарський', origin: 'Китай',
    range_km: 5, endurance_min: 28, payload_g: 50000, weight_g: 47500, speed_kmh: 50,
    battery_mah: 30000, rotors: 8,
    specs: '50 л бак. Потужніший від T30. Адаптується для скидань ВОГ та РПГ.',
    threat: 'критична',
  },
  {
    id: 79,
    name: 'DJI Mini 4 Pro',
    type: 'любительський', origin: 'Китай',
    range_km: 20, endurance_min: 34, payload_g: 0, weight_g: 249, speed_kmh: 57,
    battery_mah: 2590, rotors: 4,
    specs: '1/1.3" CMOS, 4K 100fps, HDR. До 250 г без реєстрації. Масово використовується.',
    threat: 'середня',
  },
  {
    id: 80,
    name: 'DJI Matrice 30T',
    type: 'професійний', origin: 'Китай',
    range_km: 15, endurance_min: 41, payload_g: 0, weight_g: 3770, speed_kmh: 82,
    battery_mah: 5880, rotors: 4,
    specs: 'IP55, -20°C. EO 48 Мп + тепловізор 640px. Промислова розвідка та SAR.',
    threat: 'критична',
  },
  {
    id: 81,
    name: 'Skydio 2+ (Skydio)',
    type: 'професійний', origin: 'США',
    range_km: 7, endurance_min: 27, payload_g: 0, weight_g: 800, speed_kmh: 58,
    battery_mah: 4280, rotors: 4,
    specs: 'Автономне уникнення перешкод 360°. Nvidia Xavier. ВПС США закупили партію.',
    threat: 'середня',
  },
  {
    id: 82,
    name: 'Quantum Systems Trinity F90+',
    type: 'системна', origin: 'Міжнародний',
    range_km: 100, endurance_min: 90, payload_g: 1800, weight_g: 6500, speed_kmh: 110,
    battery_mah: null, rotors: 4,
    specs: 'VTOL фіксоване крило. Запуск/посадка без злітно-посадкової смуги. LiDAR/фотограмметрія.',
    threat: 'низька',
  },
  {
    id: 83,
    name: 'WingtraOne GEN II',
    type: 'системна', origin: 'Міжнародний',
    range_km: 60, endurance_min: 59, payload_g: 800, weight_g: 3700, speed_kmh: 90,
    battery_mah: null, rotors: 2,
    specs: 'VTOL, tail-sitter конфігурація. PPK/RTK. Топографічна зйомка і 3D картографування.',
    threat: 'низька',
  },
  {
    id: 84,
    name: 'Parrot ANAFI Ai',
    type: 'системна', origin: 'Міжнародний',
    range_km: 32, endurance_min: 32, payload_g: 0, weight_g: 900, speed_kmh: 55,
    battery_mah: 6400, rotors: 4,
    specs: '48 Мп + 3× zoom + тепловізор (опція). Відкрите API ANAFI Ai SDK. NATO сертифікат.',
    threat: 'середня',
  },
  {
    id: 85,
    name: 'Aerovironment Snipe Nano',
    type: 'військовий', origin: 'США',
    range_km: 1, endurance_min: 15, payload_g: 50, weight_g: 100, speed_kmh: 40,
    battery_mah: 350,
    specs: 'Нано-БПЛА для дій у приміщеннях. Піхотне відділення. 10 cm розмах крил.',
    threat: 'середня',
  },
  {
    id: 86,
    name: 'Aerovironment Wasp AE',
    type: 'військовий', origin: 'США',
    range_km: 5, endurance_min: 50, payload_g: 200, weight_g: 430, speed_kmh: 65,
    battery_mah: 3000,
    specs: 'Малий тактичний БПЛА. Ручний запуск. EO/IR. Тихий польот. ЦРУ і SOCOM.',
    threat: 'середня',
  },
  {
    id: 87,
    name: 'MALE GNOM (UA)',
    type: 'військовий', origin: 'Україна',
    range_km: 300, endurance_min: 600, payload_g: 15000, weight_g: 55000, speed_kmh: 140,
    battery_mah: null,
    specs: 'Середній ударний БПЛА. БПЛА "Гном" від YuzhMash. Два підвіси ракет Р-60.',
    threat: 'критична',
  },
  {
    id: 88,
    name: 'Pegasus (Antonov/Ukrspecsystems)',
    type: 'військовий', origin: 'Україна',
    range_km: 100, endurance_min: 480, payload_g: 10000, weight_g: 40000, speed_kmh: 150,
    battery_mah: null,
    specs: 'Тактичний БПЛА Антонов. Реєстрація від НБКІЗ. ЕО/ІЧ. Катапультний запуск.',
    threat: 'висока',
  },
  {
    id: 89,
    name: 'Shahed-101 (Іран)',
    type: 'військовий', origin: 'Іран',
    range_km: 100, endurance_min: 90, payload_g: 5000, weight_g: 30000, speed_kmh: 200,
    battery_mah: null,
    specs: 'Малий барражуючий боєприпас. Копія/аналог RQ-170. Лопатевий гвинт.',
    threat: 'висока',
  },
  {
    id: 90,
    name: 'DJI Neo',
    type: 'любительський', origin: 'Китай',
    range_km: 8, endurance_min: 18, payload_g: 0, weight_g: 135, speed_kmh: 57,
    battery_mah: 1100, rotors: 4,
    specs: '4K 60fps. Наймалший у лінійці DJI. Без пульта. Широко доступний і дешевий.',
    threat: 'низька',
  },

  // ── РОСІЙСЬКІ FPV (Додаток 1, «FPV-рф» 2024) ────────────────────────────
  {
    id: 91,
    name: 'Бумеранг (РФ FPV)',
    type: 'FPV', origin: 'РФ',
    range_km: 10, endurance_min: 15, payload_g: 3500, weight_g: 1200, speed_kmh: 180,
    battery_mah: null, rotors: 4,
    specs: 'Важкий ударний FPV РФ. Payload 3.5 кг. Канал 433/868/915 МГц, відео 5.8 ГГц. Джерело: «FPV-рф» 2024.',
    threat: 'критична',
  },
  {
    id: 92,
    name: 'Скворець (РФ FPV)',
    type: 'FPV', origin: 'РФ',
    range_km: 10, endurance_min: 11, payload_g: 2200, weight_g: 1300, speed_kmh: 100,
    battery_mah: null, rotors: 4,
    specs: 'Ударний FPV РФ. Payload 2.2 кг. Канал 433/868/915 МГц, відео 5.8 ГГц. Джерело: «FPV-рф» 2024.',
    threat: 'критична',
  },
  {
    id: 93,
    name: 'XL-10 (РФ FPV)',
    type: 'FPV', origin: 'РФ',
    range_km: 10, endurance_min: 12, payload_g: 3500, weight_g: 1200, speed_kmh: 140,
    battery_mah: null, rotors: 4,
    specs: 'Ударний FPV РФ. Payload 3.5 кг. Канал 868/915/2400 МГц, відео 5.8 ГГц. Джерело: «FPV-рф» 2024.',
    threat: 'критична',
  },
  {
    id: 94,
    name: 'Курьер (РФ FPV)',
    type: 'FPV', origin: 'РФ',
    range_km: 10, endurance_min: 13, payload_g: 3500, weight_g: 1300, speed_kmh: 60,
    battery_mah: null, rotors: 4,
    specs: 'Тихохідний транспортний FPV РФ. Payload 3.5 кг. Канал 868/915/2400 МГц. Джерело: «FPV-рф» 2024.',
    threat: 'критична',
  },
  {
    id: 95,
    name: 'Піранья-7 (РФ FPV)',
    type: 'FPV', origin: 'РФ',
    range_km: 7, endurance_min: 13, payload_g: 2500, weight_g: 1360, speed_kmh: 125,
    battery_mah: null, rotors: 4,
    specs: '7" ударний FPV РФ. Payload 2.5 кг. Канал 868/915 МГц. Джерело: «FPV-рф» 2024.',
    threat: 'критична',
  },
  {
    id: 96,
    name: 'Піранья-10 (РФ FPV)',
    type: 'FPV', origin: 'РФ',
    range_km: 13, endurance_min: 11, payload_g: 4500, weight_g: 1490, speed_kmh: 140,
    battery_mah: null, rotors: 4,
    specs: '10" ударний FPV РФ. Payload 4.5 кг, дальність 13.3 км. Канал 868/915 МГц. Джерело: «FPV-рф» 2024.',
    threat: 'критична',
  },
  {
    id: 97,
    name: 'Химера-7 (РФ FPV)',
    type: 'FPV', origin: 'РФ',
    range_km: 10, endurance_min: 15, payload_g: 3000, weight_g: 1200, speed_kmh: 180,
    battery_mah: null, rotors: 4,
    specs: '7" FPV РФ. Payload 3.0 кг. Канал 433/868/915 МГц. Джерело: «FPV-рф» 2024.',
    threat: 'критична',
  },
  {
    id: 98,
    name: 'ПВХ-1 (РФ FPV)',
    type: 'FPV', origin: 'РФ',
    range_km: 10, endurance_min: 15, payload_g: 3000, weight_g: 1200, speed_kmh: 180,
    battery_mah: null, rotors: 4,
    specs: 'Ударний FPV РФ. Payload 3.0 кг. Канал 868/915 МГц. Джерело: «FPV-рф» 2024.',
    threat: 'критична',
  },

  // ── ISR КВАДРОКОПТЕРИ (Додаток 3, «FPV-рф» 2024) ────────────────────────
  {
    id: 99,
    name: 'DJI Air 2S',
    type: 'професійний', origin: 'Китай',
    range_km: 12, endurance_min: 31, payload_g: 0, weight_g: 595, speed_kmh: 68,
    battery_mah: 3500, rotors: 4,
    specs: '1" CMOS 5.4K. OcuSync 3. Виявлення перешкод 4 напрямки. Масово застосовується для розвідки в зоні конфлікту.',
    threat: 'висока',
  },
  {
    id: 100,
    name: 'DJI Mavic Pro Platinum',
    type: 'професійний', origin: 'Китай',
    range_km: 7, endurance_min: 30, payload_g: 0, weight_g: 734, speed_kmh: 65,
    battery_mah: 3830, rotors: 4,
    specs: '4K камера. OcuSync. Знижений рівень шуму (60 дБ). Досі активно використовується в зоні конфлікту.',
    threat: 'висока',
  },
  {
    id: 101,
    name: 'DJI Phantom 3 Standard',
    type: 'професійний', origin: 'Китай',
    range_km: 8, endurance_min: 25, payload_g: 0, weight_g: 1216, speed_kmh: 57,
    battery_mah: 4480, rotors: 4,
    specs: '2.7K відео. GPS. Третє покоління Phantom. Широко поширений, застосовується для корегування вогню.',
    threat: 'середня',
  },

  // ── КИТАЙСЬКІ УДАРНІ БПЛА (CSD Drone Databook 2020) ─────────────────────
  {
    id: 102,
    name: 'Wing Loong I (AVIC)',
    type: 'військовий', origin: 'Китай',
    range_km: 250, endurance_min: 1200, payload_g: 200000, weight_g: 1100000, speed_kmh: 280,
    battery_mah: null,
    specs: 'Китайський MALE UCAV. Аналог MQ-9 Reaper. Ракети AR-1/TL-2. Двигун Rotax 914. Експортується в ОАЕ, Єгипет, Нігерію, Саудівську Аравію.',
    threat: 'висока',
  },
  {
    id: 103,
    name: 'CH-4 (CASC)',
    type: 'військовий', origin: 'Китай',
    range_km: 250, endurance_min: 960, payload_g: 345000, weight_g: 1330000, speed_kmh: 210,
    battery_mah: null,
    specs: 'Китайський ударний БПЛА CASC. Ракети AR-1 (4 шт.). Аналог MQ-1 Predator. Ірак, ОАЕ, Нігерія.',
    threat: 'висока',
  },

  // ── ІРАНСЬКІ БПЛА (CSD Drone Databook 2020) ─────────────────────────────
  {
    id: 104,
    name: 'Shahed-129 (HESA)',
    type: 'військовий', origin: 'Іран',
    range_km: 1700, endurance_min: 1440, payload_g: 80000, weight_g: 450000, speed_kmh: 290,
    battery_mah: null,
    specs: 'Перший іранський MALE ударний БПЛА. 4 ракети Sadid-1. 24 год польоту. Двигун Rotax 912. Сирія, Ємен.',
    threat: 'критична',
  },

  // ── ТЕСТОВІ ДРОНИ SDR-ДЕТЕКЦІЇ (Sensors 2022: DronEnd Project) ──────────
  {
    id: 105,
    name: 'DJI Mavic Air',
    type: 'професійний', origin: 'Китай',
    range_km: 10, endurance_min: 21, payload_g: 0, weight_g: 430, speed_kmh: 68,
    battery_mah: 2375, rotors: 4,
    specs: '4K камера, 3-осьОВА 3D стабілізація. OcuSync+ до 10 км. Складна конструкція. Тестувався у DronEnd SDR-проєкті на частотах 2.4/5 ГГц ISM.',
    threat: 'висока',
  },
  {
    id: 106,
    name: 'DJI Mini 2',
    type: 'любительський', origin: 'Китай',
    range_km: 10, endurance_min: 31, payload_g: 0, weight_g: 249, speed_kmh: 57,
    battery_mah: 2250, rotors: 4,
    specs: '4K 30fps. До 249 г — без реєстрації. OcuSync 2.5ГГц + 5.8ГГц. Тестувався у DronEnd SDR-проєкті на 2.4/5 ГГц. Масово використовується для розвідки.',
    threat: 'середня',
  },

  // ── ІЗРАЇЛЬСЬКІ / ТУРЕЦЬКІ MALE (відкриті джерела 2024) ─────────────────
  {
    id: 107,
    name: 'Elbit Hermes 900',
    type: 'військовий', origin: 'Ізраїль',
    range_km: 300, endurance_min: 1080, payload_g: 300000, weight_g: 1180000, speed_kmh: 220,
    battery_mah: null,
    specs: 'MALE ISR БПЛА. Двигун Rotax 914. EO/IR/SAR підвіс 300 кг. 18 год польоту. Азербайджан, Чилі, Мексика. Модифікована версія Hermes 900 StarLiner.',
    threat: 'висока',
  },
  {
    id: 108,
    name: 'TAI Aksungur (Туреччина)',
    type: 'військовий', origin: 'Туреччина',
    range_km: 400, endurance_min: 2400, payload_g: 750000, weight_g: 3500000, speed_kmh: 280,
    battery_mah: null,
    specs: 'Турецький MALE UCAV. Два турбогвинтові двигуни. 40 год польоту. Керовані ракети MAM-L/MAM-C/UMTAS. Активний у ВМС Туреччини. SAR + SIGINT.',
    threat: 'висока',
  },

  // ── ІРАНСЬКІ БАРРАЖУЮЧІ (відкриті джерела 2024) ─────────────────────────
  {
    id: 109,
    name: 'HESA Ababil-3 (Іран)',
    type: 'військовий', origin: 'Іран',
    range_km: 150, endurance_min: 270, payload_g: 45000, weight_g: 83000, speed_kmh: 300,
    battery_mah: null,
    specs: 'Іранський тактичний БПЛА-камікадзе. Передвісник Shahed-136. БЧ 45 кг. Катапультний запуск з вантажівки. Хуті, ІРГК, Ємен. Двигун 2-тактний поршневий.',
    threat: 'критична',
  },

  // ── ПЕРСПЕКТИВНИЙ UA (відкриті джерела 2024) ────────────────────────────
  {
    id: 110,
    name: 'Bayraktar Kızılelma (Туреччина)',
    type: 'військовий', origin: 'Туреччина',
    range_km: 500, endurance_min: 360, payload_g: 1500000, weight_g: 6000000, speed_kmh: 800,
    battery_mah: null,
    specs: 'Перший турецький реактивний ударний БПЛА. Двигун AI-25TLT (Україна/Мотор Січ). AESA радар. Ракети ROKETSAN. Перший політ 12/2022. Авіаноскорегований.',
    threat: 'висока',
  },

  // ── НОВІ ПЛАТФОРМИ 2026 (DRONESBIIBLE каталог, відкриті джерела) ─────────
  {
    id: 111,
    name: 'Ring / KVS (РФ FPV)',
    type: 'FPV', origin: 'РФ',
    range_km: 50, endurance_min: 40, payload_g: 3000, weight_g: 5000, speed_kmh: 120,
    battery_mah: null,
    specs: 'РФ FPV з кільцевим (hula-hoop) крилом. Волоконно-оптичне керування — повна стійкість до РЕБ/джамінгу. Дальність 50 км по кабелю. Виявлено 03.2026 (EuroMaidanPress). Двигун: безщітковий BLDC.',
    threat: 'висока',
  },
  {
    id: 112,
    name: 'Пташка-18 (NextGen Defense)',
    type: 'FPV', origin: 'Україна',
    range_km: 20, endurance_min: 25, payload_g: 5000, weight_g: 9000, speed_kmh: 140,
    battery_mah: null,
    specs: 'Перший серійний 18" (46 см) важкий FPV. Волоконно-оптичне керування. Warhead 5+ кг. Захищений від РЕБ. Розроблено UA 2025–2026. Може нести кумулятивний або фугасний заряд проти бронетехніки.',
    threat: 'висока',
  },
  {
    id: 113,
    name: 'Fire Point FP-2 (UA)',
    type: 'військовий', origin: 'Україна',
    range_km: 750, endurance_min: 600, payload_g: 100000, weight_g: 280000, speed_kmh: 180,
    battery_mah: null,
    specs: 'Українська ударна платформа глибокого ураження. Корисне навантаження 100 кг. Призначена для стратегічних об\'єктів у глибині РФ. Дані 2026 (United24 Media). Поршневий/гібридний двигун.',
    threat: 'висока',
  },
  {
    id: 114,
    name: 'Shrike (UA Interceptor)',
    type: 'FPV', origin: 'Україна',
    range_km: 10, endurance_min: 15, payload_g: 500, weight_g: 1500, speed_kmh: 200,
    battery_mah: null,
    specs: 'Спеціалізований FPV-перехоплювач. Розроблений для знищення розвідувальних БПЛА та FPV противника. Висока маневреність, мінімальна БЧ. Перехоплення "дрон-дроном" без кінетичного витрачання дорогих боєприпасів.',
    threat: 'середня',
  },
  {
    id: 115,
    name: 'Wing Loong II (AVIC)',
    type: 'військовий', origin: 'Китай',
    range_km: 1500, endurance_min: 1200, payload_g: 480000, weight_g: 4200000, speed_kmh: 370,
    battery_mah: null,
    specs: 'Удосконалений MALE UCAV AVIC (Китай). 480 кг корисне навантаження. Керовані бомби/ракети TL-1/TL-2/CM-102. Проданий ОАЕ, Пакистану, Саудівській Аравії, Нігерії. Потужніший за Wing Loong I (турбогвинтовий TPE331-10G).',
    threat: 'висока',
  },
  {
    id: 116,
    name: 'Mohajer-10 (Іран)',
    type: 'військовий', origin: 'Іран',
    range_km: 2000, endurance_min: 1440, payload_g: 300000, weight_g: 700000, speed_kmh: 210,
    battery_mah: null,
    specs: 'Найновіший іранський MALE БПЛА (2023). Ендюранс 24 год. Дальність 2 000 км. КН 300 кг. Оснащений ЕО/ІЧ/SAR сенсорами. Поставлений РФ після Shahed-136. Двигун: поршневий Rotax-типу.',
    threat: 'критична',
  },
  {
    id: 117,
    name: 'Shahed-191 Saeqeh (Іран)',
    type: 'військовий', origin: 'Іран',
    range_km: 2000, endurance_min: 720, payload_g: 500000, weight_g: 900000, speed_kmh: 650,
    battery_mah: null,
    specs: 'Іранський стелс UCAV типу "flying wing". Реактивний двигун. Зовнішня підвіска 500 кг: ракети Sadid-1/Ghaem. Аналогічний компонуванню RQ-170 Sentinel (наслідування). Застосовувався у Газа/Сирія.',
    threat: 'критична',
  },
  {
    id: 118,
    name: 'Bayraktar TB3 (Туреччина)',
    type: 'військовий', origin: 'Туреччина',
    range_km: 280, endurance_min: 1440, payload_g: 280000, weight_g: 1400000, speed_kmh: 280,
    battery_mah: null,
    specs: 'Корабельна версія TB2 для ВМС Туреччини. Складне крило (авіаносець TCG Anadolu). КН 280 кг: MAM-L, UMTAS, TEBER-82. AESA Ku-діапазон. Перший серійний корабельний байрактар. Відкритий морський UAV.',
    threat: 'висока',
  },

  // ── ІНЖЕНЕРНІ / НОВІ ПЛАТФОРМИ 2026 (DRONESBIIBLE Engineering+Warfare) ──
  {
    id: 119,
    name: 'Герань-3 / Geran-3 (РФ)',
    type: 'військовий', origin: 'РФ',
    range_km: 2200, endurance_min: 720, payload_g: 50000, weight_g: 300000, speed_kmh: 500,
    battery_mah: null,
    specs: 'Новітній РФ БПЛА-камікадзе 2025 р. (апгрейд Shahed-136). Китайський турбофанний двигун — швидкість до 500 км/год. Mesh WiFi для роєвої координації без центрального вузла. Вбудовані AI-процесори для автономного цілевозначення. OSINT Q4 2025: drone-warfare.com.',
    threat: 'критична',
  },
  {
    id: 120,
    name: 'STM Kargu-2 (Туреччина)',
    type: 'військовий', origin: 'Туреччина',
    range_km: 5, endurance_min: 30, payload_g: 1500, weight_g: 7000, speed_kmh: 130,
    battery_mah: null,
    specs: 'Турецький автономний барражуючий боєприпас. AI-виявлення цілей без оператора (autonomous lethal drone). Застосований у Лівії 2020 (перше зафіксоване автономне вбивство БПЛА). 4 лопасті. БЧ кумулятивна 1.5 кг. Виробник STM (Defence Technologies).',
    threat: 'критична',
  },
  {
    id: 121,
    name: 'MQ-1C Gray Eagle (General Atomics)',
    type: 'військовий', origin: 'США',
    range_km: 400, endurance_min: 1680, payload_g: 488000, weight_g: 1633000, speed_kmh: 280,
    battery_mah: null,
    specs: 'US Army MALE БПЛА (наступник MQ-1 Predator). 28 год польоту. КН 488 кг: AGM-114 Hellfire ×4. Двигун Thielert Centurion 1.7 (дизель). FLIR МTS-B. Link-16 та SATCOM. Застосовується у Іраку, Афганістані, Сирії. Запропонований Україні 2022 (відхилено).',
    threat: 'висока',
  },
  {
    id: 122,
    name: 'RQ-4 Global Hawk (Northrop)',
    type: 'військовий', origin: 'США',
    range_km: 22780, endurance_min: 2160, payload_g: 1360000, weight_g: 14628000, speed_kmh: 575,
    battery_mah: null,
    specs: 'Стратегічний ISR БПЛА США. Висота польоту 18 км (60 000 ft). 36 год ендюранс. SAR + GMTI + SIGINT sensors (HISAR, MS-177). Wingspan 39.9 м. Турбофан Rolls-Royce AE3007H. Активно моніторює Чорне море/фронт UA. Блок-40: BACN комунікаційне реле.',
    threat: 'середня',
  },
  {
    id: 123,
    name: 'WZ-7 Soaring Dragon (Китай)',
    type: 'військовий', origin: 'Китай',
    range_km: 7000, endurance_min: 600, payload_g: 650000, weight_g: 7500000, speed_kmh: 750,
    battery_mah: null,
    specs: 'Китайський стратегічний ISR БПЛА (аналог RQ-4). Flying wing компонування. Висота 18+ км. Турбофан WS-17. Оснащений SAR, SIGINT, IMINT. Відстежений над Тихим океаном та Корейським п-овом. Виробник: Chengdu Aircraft Industry Group.',
    threat: 'висока',
  },
  {
    id: 124,
    name: 'Forpost-M (РФ)',
    type: 'військовий', origin: 'РФ',
    range_km: 250, endurance_min: 600, payload_g: 120000, weight_g: 500000, speed_kmh: 200,
    battery_mah: null,
    specs: 'Модернізований РФ ISR/ударний БПЛА (апгрейд Forpost-RU). Повністю вітчизняний двигун МДТУРБ (замість IAI). КН 120 кг — підвіска ударних боєприпасів. EO/IR/SAR комплекси. Дальність передачі відео 250 км. Активний Українській фронт 2022–2026.',
    threat: 'висока',
  },
  {
    id: 125,
    name: 'Crazyflie 2.1 (Bitcraze)',
    type: 'любительський', origin: 'Міжнародний',
    range_km: 0.1, endurance_min: 7, payload_g: 15, weight_g: 27, speed_kmh: 30,
    battery_mah: 250,
    specs: 'Open-source nano-квадрокоптер для досліджень (Bitcraze, Швеція). Маса 27 г. LiPo 250 мАг. STM32F405 + nRF51822. Підтримка ROS2, Python, Simulink. Застосований у SkySim (2026, ArXiv 2602.01226): роєве керування LLM Gemini 3.5 для груп 3/10/30 дронів. Базова платформа для swarm-R&D.',
    threat: 'низька',
  },
  {
    id: 126,
    name: 'Fiber-optic Sleeper / Gibernator (UA)',
    type: 'FPV', origin: 'Україна',
    range_km: 20, endurance_min: 180, payload_g: 3000, weight_g: 5000, speed_kmh: 60,
    battery_mah: null,
    specs: 'Українська FPV-платформа на основі волоконно-оптичного кабелю. Режим standby: дрон залишається на місці у сплячому режимі, активується за командою — повна стійкість до радіоелектронної боротьби. Застосовується для засідок на танки/техніку. Дальність визначається довжиною кабелю (до 20 км). Проект підтриманий Міноборони UA.',
    threat: 'висока',
  },
  {
    id: 127,
    name: '$1,000 Interceptor (UA)',
    type: 'FPV', origin: 'Україна',
    range_km: 5, endurance_min: 15, payload_g: 500, weight_g: 800, speed_kmh: 180,
    battery_mah: 2200,
    specs: 'Масовий UA FPV-перехоплювач вартістю ~$1 000. Розроблений як відповідь на ворожі FPV-атаки. Привернув увагу Пентагону як модель масово доступного anti-FPV рішення. Висока маневреність, час реакції <30 с. Потенційне масове виробництво для насичення лінії фронту.',
    threat: 'висока',
  },
  {
    id: 128,
    name: 'Deftak / OFAB-100-110-TU (UA)',
    type: 'військовий', origin: 'Україна',
    range_km: 80, endurance_min: 60, payload_g: 121000, weight_g: 200000, speed_kmh: 350,
    battery_mah: null,
    specs: 'Українська система наведення Deftak для авіабомби OFAB-100-110-TU. Маса БЧ 121 кг. Перетворює нерегульовані авіабомби на керовані високоточні боєприпаси. Дальність застосування до 80 км залежно від висоти скидання. Аналог JDAM-ER. Активно застосовується ПС ЗСУ 2025–2026.',
    threat: 'критична',
  },
]

export const droneTypeColors: Record<DroneType, string> = {
  'FPV':                 'border-red-500/30 bg-red-500/10 text-red-400',
  'військовий':          'border-amber-500/30 bg-amber-500/10 text-amber-400',
  'професійний':         'border-ecalc-orange/30 bg-ecalc-orange/10 text-ecalc-orange',
  'любительський':       'border-ecalc-green/30 bg-ecalc-green/10 text-ecalc-green',
  'сільськогосподарський':'border-purple-500/30 bg-purple-500/10 text-purple-400',
  'кінематографічна':    'border-sky-500/30 bg-sky-500/10 text-sky-400',
  'системна':            'border-ecalc-border bg-ecalc-lightbg text-ecalc-muted',
}

export const threatColors: Record<ThreatLevel, string> = {
  'низька':    'text-ecalc-green',
  'середня':   'text-amber-400',
  'висока':    'text-ecalc-orange',
  'критична':  'text-red-400',
}

export const originFlag: Record<Origin, string> = {
  'Україна':      '🇺🇦',
  'РФ':           '🇷🇺',
  'Іран':         '🇮🇷',
  'США':          '🇺🇸',
  'Туреччина':    '🇹🇷',
  'Китай':        '🇨🇳',
  'Ізраїль':      '🇮🇱',
  'Польща':       '🇵🇱',
  'Міжнародний':  '🌐',
}

export type DronePrefill = {
  name: string
  auwG: number
  capacityMah: number
  rangeKm: number
  enduranceMin: number
  rotors: number
}

export const DRONE_PREFILL_KEY = 'ecalc-drone-prefill-v2'

// База даних v1.3 — 128 платформ
