import { PerfCalcInput, airDensity, propCtStatic, staticThrustFromCt } from '@/lib/aero'

function withDerived(input: Omit<PerfCalcInput, 'staticThrustG'>): PerfCalcInput {
  const density = airDensity(input.elevationM, input.temperatureC)
  const ct = input.ctStaticOverride ?? propCtStatic(input.propDiameterIn, input.propPitchIn, input.bladeCount)
  return {
    ...input,
    staticThrustG: staticThrustFromCt(ct, density, input.rpm, input.propDiameterIn) * input.motorCount,
  }
}

export const perfCalcPresets = [
  {
    id: 'foamie',
    name: '1 м foamie trainer',
    description: 'Легкий тренер для спокійного польоту та базових розрахунків дальності.',
    expected: {
      stallSpeedKmh: '26-29',
      pitchSpeedKmh: '78-84',
      bestRangeKmh: '42-48',
      maxRocMs: '4.5-6.0',
    },
    input: withDerived({
      elevationM: 250,
      temperatureC: 20,
      weightKg: 1.35,
      wingAreaDm2: 26,
      wingSpanMm: 1080,
      cd0: 0.034,
      oswald: 0.82,
      clMax: 1.45,
      motorCount: 1,
      propDiameterIn: 10,
      propPitchIn: 6,
      bladeCount: 2,
      rpm: 9200,
      drivePowerW: 460,
      batteryCells: 3,
      batteryVoltagePerCell: 3.7,
      batteryCapacityMah: 2200,
      averageCurrentA: 22,
    }),
  },
  {
    id: '3d',
    name: '3D aerobatic 60E',
    description: 'Акробатична модель з високою статичною тягою та запасом по ROC.',
    expected: {
      stallSpeedKmh: '33-37',
      pitchSpeedKmh: '96-105',
      bestRangeKmh: '52-58',
      maxRocMs: '15-20',
    },
    input: withDerived({
      elevationM: 500,
      temperatureC: 25,
      weightKg: 3.9,
      wingAreaDm2: 62,
      wingSpanMm: 1580,
      cd0: 0.038,
      oswald: 0.79,
      clMax: 1.58,
      motorCount: 1,
      propDiameterIn: 17,
      propPitchIn: 8,
      bladeCount: 2,
      rpm: 7600,
      drivePowerW: 1750,
      batteryCells: 6,
      batteryVoltagePerCell: 3.7,
      batteryCapacityMah: 5000,
      averageCurrentA: 58,
    }),
  },
  {
    id: 'glider',
    name: 'Fast electric glider',
    description: 'Швидкісний планер з помірним опором і хорошою дальністю за Карсоном.',
    expected: {
      stallSpeedKmh: '30-34',
      pitchSpeedKmh: '135-148',
      bestRangeKmh: '49-56',
      maxRocMs: '7-10',
    },
    input: withDerived({
      elevationM: 300,
      temperatureC: 18,
      weightKg: 2.4,
      wingAreaDm2: 38,
      wingSpanMm: 2100,
      cd0: 0.026,
      oswald: 0.87,
      clMax: 1.35,
      motorCount: 1,
      propDiameterIn: 13,
      propPitchIn: 10,
      bladeCount: 2,
      rpm: 9800,
      drivePowerW: 1050,
      batteryCells: 4,
      batteryVoltagePerCell: 3.7,
      batteryCapacityMah: 3200,
      averageCurrentA: 38,
    }),
  },
  {
    id: 'warbird',
    name: 'Warbird sport scale',
    description: 'Масштабна швидкісна модель з вищим Cd0 і нижчим запасом тяги.',
    expected: {
      stallSpeedKmh: '39-44',
      pitchSpeedKmh: '118-128',
      bestRangeKmh: '57-63',
      maxRocMs: '5-7',
    },
    input: withDerived({
      elevationM: 100,
      temperatureC: 22,
      weightKg: 4.6,
      wingAreaDm2: 58,
      wingSpanMm: 1460,
      cd0: 0.046,
      oswald: 0.75,
      clMax: 1.42,
      motorCount: 1,
      propDiameterIn: 15,
      propPitchIn: 10,
      bladeCount: 3,
      rpm: 8100,
      drivePowerW: 1450,
      batteryCells: 6,
      batteryVoltagePerCell: 3.7,
      batteryCapacityMah: 4500,
      averageCurrentA: 52,
    }),
  },
]

export const defaultPerfCalcInput = perfCalcPresets[1].input
